[workspace]
git_release_enable = false # create GitHub release
git_tag_enable = false 
allow_dirty = true # allow updating repositories with uncommitted changes
changelog_config = ".cliff.toml" # use a custom git-cliff configuration
dependencies_update = false # update dependencies with `cargo update`
pr_labels = ["release"]
semver_check = true
publish_timeout = "10m" # set a timeout for `cargo publish`

[[package]] 
name = "redis_config"
git_tag_enable = true 
changelog_path = "./CHANGELOG.md"
git_release_enable = true # create GitHub release